---
? ''
: octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: v=spf1 -all
'*._domainkey':
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: v=DKIM1\; p=
_dmarc:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: v=DMARC1\; p=reject\; sp=reject\; adkim=s\; aspf=s\;
netbox:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: A
  value: 45.32.195.245
