---
? ''
: - octodns:
      cloudflare:
        auto-ttl: true
    ttl: 300
    type: MX
    values:
    - exchange: aspmx.l.google.com.
      preference: 1
    - exchange: alt1.aspmx.l.google.com.
      preference: 5
    - exchange: alt2.aspmx.l.google.com.
      preference: 5
    - exchange: alt3.aspmx.l.google.com.
      preference: 10
    - exchange: alt4.aspmx.l.google.com.
      preference: 10
  - octodns:
      cloudflare:
        auto-ttl: true
    ttl: 300
    type: TXT
    value: v=spf1 include:_spf.google.com ~all
_dmarc:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: v=DMARC1\; p=none\; rua=mailto:24a8ddb966d04981be2cfd610fc0d26d@dmarc-reports.cloudflare.net\;
calendar:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: CNAME
  value: ghs.googlehosted.com.
drive:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: CNAME
  value: ghs.googlehosted.com.
google._domainkey:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  values:
  - 7zaWEYLYuQ9L6C6NRK/yMuAfGI4erKNjPKgXla1+3VwB1/TCuit5oG8yzQJLHnsuA4CpF7YhNfp8+EGzPBIdVveGBh84ExqhIy7FTB0SMCgW65O8xpudEAyHqfsfMsX1w4sglOo31Tb+Z28TCoesQIDAQAB
  - v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtMhSI3e6fpWofjQm/OQYBABLLMgiq8Mtdq//Zh68x6t8voPinWZAbzhTmIgCRvINrxVuUQN6t7Z6q7+yVhp3YowyqlqAWANmu2zzoNTcBopBK0uMT72tLRlDxuuuYN64AjQT0/Sc3Yh8S6eOjqLo5odqdlUE6/JOvoqcUe7X35tDGzEdMvgS0hCqKaGJ3XkdM
mail:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: CNAME
  value: ghs.googlehosted.com.
netbox:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: CNAME
  value: 45.32.195.245.vultrusercontent.com.
