name: build docker release

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'release/**'
      - 'hotfix/**'
    tags:
      - '*'
    # paths:
    #   - 'zones/config/**'
    #   - 'zones/internal/**'
    #   - 'zones/secret/**'

jobs:
  version:
    name: Build modified chart
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: gittools/actions/gitversion/execute@v0
      id: gitversion

  release-lite:
    name: Release zones-lite
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          sudo mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops
      - uses: actions/setup-python@v5
      - run: pip install -r requirements.txt
      - run: make release VERSION=internal DOIT=true
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY_FILE }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v4
        id: metadata-slim
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/zones
          tags: |
            type=semver,pattern={{raw}},value=${{ needs.version.outputs.version }}-slim
          labels: |
            org.opencontainers.image.description=CoreDNS Server
            org.opencontainers.image.authors=Ganawa Juanah(ganawa@juanah.com)
            org.opencontainers.image.url=github.com/ganawaj/zones
            org.opencontainers.image.version=${{ needs.version.outputs.version }}-slim
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: build/docker/Dockerfile
          push: true
          tags: ${{ steps.metadata-slim.outputs.tags }}
          labels: ${{ steps.metadata-slim.outputs.labels }}

  releasee:
    name: Release zones full
    runs-on: ubuntu-latest
    needs:
      - version
      - release-lite
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/zones
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{raw}},value=${{ needs.version.outputs.version }}
          labels: |
            org.opencontainers.image.description=CoreDNS Server
            org.opencontainers.image.authors=Ganawa Juanah(ganawa@juanah.com)
            org.opencontainers.image.url=github.com/ganawaj/zones
            org.opencontainers.image.version=${{ needs.version.outputs.version }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: build/docker/Dockerfile.dns
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            ZONE_VERSION=${{ needs.version.outputs.version }}
            COREDNS_VERSION="1.11.2"